###
POST http://localhost:8080/api/v1/actors/create
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="actor"
Content-Type: application/json

{
  "name": "Tom Hanks"
}
--boundary123
Content-Disposition: form-data; name="image"; filename="tom.jpg"
Content-Type: image/jpeg

< ./test.png
--boundary123--
