### User Registration Request
POST http://localhost:8080/api/v1/auth/user/register
Content-Type: application/json

{
  "email": "dhamaladeepgmail.com",
  "password": "appleisredU1@",
  "username": "apple2"
}

### User Authentication Request
POST http://localhost:8080/api/v1/auth/user/authenticate
Content-Type: application/json

{
  "email": "dhamaladeep@gmail.com",
  "password": "appleisredU1@"
}


###
POST http://localhost:8080/api/v1/auth/user/exchange-authcode-for-tokens
Content-Type: application/json

{
  "authorizationCode": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaGFtYWxhZGVlcEBnbWFpbC5jb20iLCJpYXQiOjE3NDk5MjAwNDksImV4cCI6MTc0OTkyMDA3OSwidHlwZSI6Ik9ORV9USU1FX1RPS0VOIn0.IJJIAoKoOpAwiHjQN85tP7__dot1pGB41lJamdLbAtw"
}

###
POST http://localhost:8080/api/v1/auth/user/verify-otp
Content-Type: application/json

{
  "email": "dhamaladeep@gmail.com",
  "otp": "527391"
}